import "./globals.css";

// const rubic = Rubik({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800", "900"],
//   display: "swap",
//   variable: "--font-rubic",
// });

export const metadata = {
  title: "Parth Institute - SPREADING KNOWLEDGE...",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="LTR">
      <body >{children}</body>
    </html>
  );
}
